# Generated by Django 4.0.2 on 2022-04-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_recipe_description_recipe_difficulty_recipe_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='username',
            field=models.CharField(default='no_name', max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
