# Generated by Django 4.0.2 on 2022-04-07 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_date_created_userfavoriterecipe_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('instruction', models.TextField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='api.recipe')),
            ],
        ),
        migrations.AlterField(
            model_name='userfavoriterecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_to', to='api.recipe'),
        ),
        migrations.AlterUniqueTogether(
            name='userfavoriterecipe',
            unique_together={('account', 'recipe')},
        ),
        migrations.DeleteModel(
            name='Direction',
        ),
    ]
