# Generated by Django 4.0.2 on 2022-04-09 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_instruction_options_alter_instruction_order_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserFavoriteRecipe',
            new_name='AccountFavoriteRecipe',
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-date_created']},
        ),
    ]
