# Generated by Django 4.0.2 on 2022-04-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_ingredient_amount_alter_ingredient_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountfavoriterecipe',
            options={'ordering': ['-date_added']},
        ),
        migrations.AddField(
            model_name='recipe',
            name='cuisine',
            field=models.CharField(choices=[('assian', 'Asian'), ('japanese', 'Japanese'), ('chinese', 'Chinese'), ('korean', 'Korean'), ('indian', 'Indian'), ('seafood', 'Seafood'), ('mexican', 'Mexican'), ('american', 'American'), ('italian', 'Italian'), ('british', 'British'), ('french', 'French'), ('greek', 'Greek'), ('slovak', 'Slovak'), ('african', 'African')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
