# Generated by Django 4.0.2 on 2022-04-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_accountfavoriterecipe_options_recipe_cuisine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cuisine',
            field=models.CharField(blank=True, choices=[('asian', 'Asian'), ('japanese', 'Japanese'), ('chinese', 'Chinese'), ('korean', 'Korean'), ('indian', 'Indian'), ('seafood', 'Seafood'), ('mexican', 'Mexican'), ('american', 'American'), ('italian', 'Italian'), ('british', 'British'), ('french', 'French'), ('greek', 'Greek'), ('slovak', 'Slovak'), ('african', 'African')], max_length=20, null=True),
        ),
    ]
