# Generated by Django 4.0.2 on 2022-02-26 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='last_login',
        ),
    ]
