# Generated by Django 4.0.2 on 2022-02-26 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook_api', '0003_alter_account_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='onboarded',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directions', models.TextField()),
                ('category', models.CharField(choices=[('raňajky', 'Breakfast'), ('obed', 'Lunch'), ('zákusok', 'Dessert'), ('slovenská kuchyňa', 'Slovak Cuisine'), ('ázijská kuchyňa', 'Asian Cuisine'), ('talianska kuchyňa', 'Italian Cuisine'), ('iné', 'Other')], default='iné', max_length=32, null=True)),
                ('prep_time', models.IntegerField(null=True)),
                ('cook_time', models.IntegerField(null=True)),
                ('servings', models.IntegerField(null=True)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='cookbook_api.account')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=4)),
                ('unit', models.CharField(max_length=16)),
                ('note', models.TextField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='cookbook_api.recipe')),
            ],
        ),
    ]
