# Generated by Django 4.0.2 on 2022-02-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook_api', '0004_comment_account_onboarded_recipe_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
    ]
