# Generated by Django 4.0.2 on 2022-02-26 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook_api', '0005_alter_ingredient_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='cookbook_api.account'),
        ),
    ]
