# Generated by Django 4.0.2 on 2022-02-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook_api', '0006_alter_recipe_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='title',
            field=models.CharField(default='title', max_length=128),
            preserve_default=False,
        ),
    ]
