# Generated by Django 4.0.2 on 2022-02-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook_api', '0007_recipe_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
