# Generated by Django 4.0.2 on 2022-03-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook_api', '0009_alter_ingredient_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.CharField(max_length=20),
        ),
    ]
