# Generated by Django 4.0.2 on 2022-03-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook_api', '0010_alter_ingredient_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cook_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='dislikes',
            field=models.IntegerField(blank=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='likes',
            field=models.IntegerField(blank=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='servings',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
