# Generated by Django 4.0.2 on 2022-03-06 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook_api', '0012_delete_comment_alter_recipe_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='cookbook_api.account'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(editable=False)),
                ('likes', models.IntegerField(blank=True, default=0, editable=False)),
                ('dislikes', models.IntegerField(blank=True, default=0, editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='cookbook_api.account')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='cookbook_api.recipe')),
            ],
        ),
    ]
